[tools]
cocoapods = "1.15.2"
node = "20.12.2"
ruby = "3.2"
yarn = "1.22.22"

[tasks.install-deps]
description = "Install dependencies"
run = """
#!/usr/bin/env zsh
yarn install
"""

[tasks.dev]
description = "Run dev"
run = """
#!/usr/bin/env zsh
yarn dev
"""

[tasks.format]
description = "Format code using Biome"
run = """
#!/usr/bin/env zsh
yarn format
"""

[tasks.lint]
description = "Lint code using Biome"
run = """
#!/usr/bin/env zsh
yarn lint
"""

[tasks.check]
description = "Check and fix code using Biome"
run = """
#!/usr/bin/env zsh
yarn check
"""

[tasks.prebuild]
description = "Check and fix code using Biome"
run = """
#!/usr/bin/env zsh
yarn prebuild
"""
